language: node_js
node_js:
  - "6.x"
sudo: false
env:
  global:
    - REGION=us
    - APP_ID=WI5a89CtPIOrWpvIwzNfOg9R-MdYXbMMI
    - APP_KEY=RUoMOSD8RNlpd0MIIiSDi7BU
install:
  - npm i -g typescript typings
  - npm install
  - typings install
script:
  - npm test
notifications:
  webhooks: https://hook.bearychat.com/=bw52Y/travis/0ce0c78a1e423b087df137fcbfbf619f